services:
  auth-service:
    build: .
    ports:
      - '5001:5001'
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=False
      - SECRET_KEY=your-secret-key-here
    volumes:
      - .:/app
    networks:
      - auth-network

  prometheus:
    image: prom/prometheus:latest
    container_name: auth-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - '9091:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - auth-network

volumes:
  prometheus_data:

networks:
  auth-network:
    driver: bridge 